publish_water_usage:
  description: передача показаний воды в моспортал
  fields:
    meter_list_to_update:
      description: Опционально, месяц, за который надо получить ЕПД
      example:
        - meter_id: 'id счетчика'
          value: 123.7
          friendly_name: 'наименование счетчика (для отображения в event)'


get_epd:
  description: получение ЕПД с моспортала и отправка его в канал mqtt
  fields:
    month:
      # Description of the field
      description: Опционально, месяц, за который надо получить ЕПД
      # Example value that can be passed for this field
      example: '12'
    year:
      description: год
      example: '2019'
    data:
      description: любые данные в формате json
      example: "{'user_id':'123','message_id':'132'}"
    payload:
      description: payload для получения ЕПД (можно не указывать, если в ЛК есть только один ЕПД)
      example: 1231231231